### ISSUE TITLE
GPU index error

### ISSUE THREAD

**Issue by andre-merzky** [MatthiasSchinzel/sysmon#3]
I see this error:
```sh
$ python3 -V
Python 3.6.9

$ uname -a
Linux xxx 5.0.0-1043-oem-osp1 #48-Ubuntu SMP Thu Mar 12 09:53:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ python3 sysmon.py
Traceback (most recent call last):
  File "sysmon.py", line 593, in <module>
    main()
  File "sysmon.py", line 587, in main
    main = MainWindow()
  File "sysmon.py", line 216, in __init__
    self.update_gpuinfo()
  File "sysmon.py", line 525, in update_gpuinfo
    num = data[gpu_ind][4]
IndexError: list index out of range
```

Let me know if you need additional information.

**Comment by andre-merzky** [comment]
Looking a bit further, this seems to happen because I have a disabled nvidia card - `nvidia-smi` will not return any data in this case.  You should check if any data are returned there...

```sh
$ nvidia-smi
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```

**Comment by MatthiasSchinzel** [comment]
Thanks for the submission! I will add this, please give me a few moments!

**Comment by MatthiasSchinzel** [comment]
Please try again now!

**Comment by andre-merzky** [comment]
Looks good now - thanks! :-)

**Comment by rany2** [comment]
```
user@debian~/D/s/src> python3 ./sysmon.py
Traceback (most recent call last):
  File "./sysmon.py", line 593, in <module>
    main()
  File "./sysmon.py", line 587, in main
    main = MainWindow()
  File "./sysmon.py", line 101, in __init__
    self.s = sysinfo()
  File "/home/user/Downloads/sysmon/src/gather_data.py", line 54, in __init__
    self.check_for_nvidia_smi()
  File "/home/user/Downloads/sysmon/src/gather_data.py", line 175, in check_for_nvidia_smi
    ps = str(subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nvidia-smi'
```

**Comment by rany2** [comment]
Could this issue be reopened? The latest commit breaks this application so it actually introduces another problem.

**Comment by MatthiasSchinzel** [comment]
Yes sure. Sorry, wrong indentation. Should be fixed now.

**Comment by rany2** [comment]
I could confirm it's fixed. Thank you :smile:

**Comment by MatthiasSchinzel** [comment]
Great, thanks!
