### ISSUE TITLE
I have an error..

### ISSUE THREAD

**Issue by anysystemroot** [MatthiasSchinzel/sysmon#32]
$ pip install sysmon

$ sysmon

Traceback (most recent call last):
  File "/home/username/.local/bin/sysmon", line 8, in <module>
    sys.exit(main())
  File "/home/username/.local/lib/python3.10/site-packages/sysmon/sysmon.py", line 607, in main
    main = MainWindow()
  File "/home/username/.local/lib/python3.10/site-packages/sysmon/sysmon.py", line 119, in __init__
    header.setResizeMode(QtGui.QHeaderView.ResizeToContents)
AttributeError: 'QHeaderView' object has no attribute 'setResizeMode'. Did you mean: 'ResizeMode'?

# i try uninstall it and use "pip3 install sysmon", but i have this error again.

**Comment by henriquedesousa** [comment]
Fixed here: https://github.com/MatthiasSchinzel/sysmon/issues/31
